import { styleCSS } from './style.js';
import { ctx } from './store.js';
import * as All from './all.js';
import { BLOCK_PRICE_PG, WEATHERS, TEST_MODE, DAY_MS, CROPS, GROW, MIN, REGROW, FERTS, WATER_CD, REGROW_MAX, POKE_CD, TREASURE_CD, PETS_OUT_MAX, WITCH_STAY, witchGap, SNAP_EDGE, ZONE_NAME } from './data.js';
import { mulberry32, petSVG, spriteSVG, tileURI, warmUpCache, PETS, PASSES, P, LP, PET_P } from './graphics.js';

X: "#fff2bd",
T: "#8b5936",
ctx.S: "#d99a43",
Q: "#76545f",
H: "#56649d",
h: "#8492c7",
Y: "#f5d76d",
y: "#bd923b",
O: "#fffaf0",
q: "#cfc5df",
Z: "#72d4c7",
c: "#3fa6a5",
a: "#bff3df",
k: "#688f57",
l: "#a6cb7d",
i: "#c8d8f0",
j: "#8296c9",
x: "#8e6bad",
m: "#d9bd6f",
u: "#dcf3e7",
s: "#92c4b0"
};
var PET_SPR = {
slime: [
  "................",
  "................",
  "................",
  "................",
  ".....BBBBBB.....",
  "....BBBBBBBB....",
  "...BBWWBBBBBB...",
  "..BBWWBBBBBBBB..",
  "..BBBBBBBBBBBB..",
  "..BB33BBBB33BB..",
  ".BBBBBBBBBBBBBB.",
  ".BnBBBB33BBBBnB.",
  ".BBBBBBBBBBBBBB.",
  ".bBBBBBBBBBBBBb.",
  "..bbbbbbbbbbbb..",
  "................"
],
slimePink: [
  "................",
  "................",
  "................",
  "................",
  ".....pppppp.....",
  "....pppppppp....",
  "...ppWWpppppp...",
  "..ppWWpppppppp..",
  "..pppppppppppp..",
  "..ppffppppffpp..",
  ".pppppppppppppp.",
  ".pFppppffppppFp.",
  ".pppppppppppppp.",
  ".FppppppppppppF.",
  "..FFFFFFFFFFFF..",
  "................"
],
slimeNight: [
  ".......O........",
  "......OOO.......",
  ".......t........",
  ".....TTTTTT.....",
  "....TTTTTTTT....",
  "...TCTTTTTTTT...",
  "..TCTTTTTTTTTT..",
  ".TTTTDTTTTDTTTT.",
  ".TTPPTTDDTTPPTT.",
  ".TTTTTTTTTTTTTT.",
  "..tTTTTTTTTTTt..",
  ".tTT.tTTTT.tTTt.",
  "tTt..tTTt..tTTt.",
  ".t...tT.tT...tT.",
  ".....t...t......",
  "................"
],
octo: [
  "................",
  "................",
  "................",
  ".....VVVVVV.....",
  "....VVVVVVVV....",
  "...VVWWVVVVVV...",
  "...VWWVVVVVVV...",
  "..VVVVVVVVVVVV..",
  "..VVKKVVVVKKVV..",
  "..VVVVVVVVVVVV..",
  "..VnVVVKKVVVnV..",
  "..VVVVVVVVVVVV..",
  "..VVVVVVVVVVVV..",
  "..VV.VV..VV.VV..",
  "..vv.vv..vv.vv..",
  "................"
],
octoCream: [
  "................",
  "................",
  "................",
  ".....AAAAAA.....",
  "....AAAAAAAA....",
  "...AAWWAAAAAA...",
  "...AWWAAAAAAA...",
  "..AAAAAAAAAAAA..",
  "..AAAAAAAAAAAA..",
  "..AAKKAAAAKKAA..",
  "..AnAAAAAAAAnA..",
  "..AAAAAAAAAAAA..",
  "..AAAAAAAAAAAA..",
  "..AA.AA..AA.AA..",
  "..zz.zz..zz.zz..",
  "................"
],
bunny: [
  "......S.........",
  ".....SSS........",
  "......S.........",
  ".....IIIIII.....",
  "....IIIIIIII....",
  "...IIBIIIIIII...",
  "..IIBIIIIIIIII..",
  ".IIIIYIIIIYIIII.",
  ".IIPPIISSIIPPII.",
  ".IIIIIIIIIIIIII.",
  "..iIIIIIIIIIIi..",
  "...iiiiiiiiii...",
  "...LL..LL..LL...",
  "..LL...LL...LL..",
  "..L....L....L...",
  ".LL...LL...LL..."
],
batBlob: [
  "................",
  "...oo......oo...",
  "...ooo....ooo...",
  "...oooo..oooo...",
  "....oooooooo....",
  "...oooooooooo...",
  "..oooooooooooo..",
  "..ooKKooooKKoo..",
  "ttooooonnooooott",
  ".toooooooooooot.",
  ".onoooooooooono.",
  ".oooooooooooooo.",
  ".oooooooooooooo.",
  ".toooooooooooot.",